version: "3.3"
services:
  app:
    image: my_image:v1.2
    container_name: img1
    ports:
      - "8080:81"
    tty: true
    restart: always

  web-server:
    image: nginx
    container_name: mynginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/:/etc/nginx/
    tty: true
    restart: always
